In [215]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import classification_report
from matplotlib import pyplot as pltgraph
from sklearn import tree

In [216]:
col_names = ['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothead', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize', 'type']
ds=pd.read_csv("zoo_data(1).csv", header=None, names=col_names)

In [217]:
ds.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothead  \
0     1         0     0     1         0        0         1         1   
1     1         0     0     1         0        0         0         1   
2     0         0     1     0         0        1         1         1   
3     1         0     0     1         0        0         1         1   
4     1         0     0     1         0        0         1         1   

   backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         1         0     0     4     0         0        1     1  
1         1         1         0     0     4     1         0        1     1  
2         1         0         0     1     0     1         0        0     4  
3         1         1         0     0     4     0         0        1     1  
4         1         1         0     0     4     1         0        1     1

In [218]:
X=ds.values[:,:16]

In [219]:
X

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]])

In [220]:
Y=ds.values[:,-1]

In [221]:
Y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2])

In [222]:
len(ds)

101

In [205]:
len(Y)

101

In [206]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [207]:
clf = DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)

In [208]:
print("Accuracy:",clf.score(X_test, Y_test))

Accuracy: 0.967741935483871


In [209]:
clf

DecisionTreeClassifier(criterion='entropy')

In [210]:
clf = DecisionTreeClassifier(criterion='gini')
clf = clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)

In [211]:
print("Accuracy:",clf.score(X_test, Y_test))

Accuracy: 0.967741935483871


In [212]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         7
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         2
           6       0.75      1.00      0.86         3
           7       1.00      0.67      0.80         3

    accuracy                           0.97        31
   macro avg       0.96      0.94      0.94        31
weighted avg       0.98      0.97      0.97        31



In [213]:
print(confusion_matrix(Y_test,Y_pred))

[[12  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0  4  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  1  2]]


In [214]:
class_names=["class1","class2","class3","class4","class5","class6","class7"]
_=tree.plot_tree(clf,feature_names=col_names,class_names=class_names,filled=True)

NameError: name 'tree' is not defined